### ISSUE TITLE
画像読み込みの際に特定の挙動を行うとエラーが発生する

### ISSUE THREAD

**Issue by Yuto0628** [Yuto0628/image_pixel_sampling#35]
1.[ファイルを選択]を押してローカルファイルから画像を選択する
2.再度[ファイルを選択]を押して画像を選択せずにローカルファイルを閉じる

上記の手順を行うと以下のエラーが発生することを確認した
Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

現状エラーが発生しても次の画像の読み込みなどには影響が無いように見えるけど直せるなら解決してくれると嬉しいです

**Comment by Yuto0628** [comment]
エラー発生箇所

at draw_canvas (index.js:29:16)
    at HTMLInputElement.<anonymous> (index.js:3:5)
